# Generated by Django 4.2.1 on 2023-07-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_options_alter_profile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='\\users\\profile-42914_640.webp', null=True, upload_to='users/'),
        ),
    ]
