# Generated by Django 4.2.1 on 2023-05-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='owner',
            new_name='user',
        ),
    ]
